spring:
  datasource:
    url: jdbc:mysql://mysqldb:3306/justrandomdata
#    url: jdbc:mysql://localhost:3306/justrandomdata
#    username: root
    username: random
#    password: admin
    password: random
    driver-class-name: com.mysql.cj.jdbc.Driver
#  flyway:
#    enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        ddl-auto: update
        show-sql: true